// GENERATED by docs/design/identity/build/dart_tokens.py from docs/design/identity/c-minimal/tokens.json.
// Do not edit by hand: change the tokens source and regenerate. A test compares this file with the JSON.
import 'package:flutter/material.dart';

@immutable
class AppColors extends ThemeExtension<AppColors> {
  const AppColors({
    required this.bg,
    required this.surface,
    required this.container,
    required this.ink,
    required this.muted,
    required this.line,
    required this.outline,
    required this.primary,
    required this.onPrimary,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.accent,
    required this.onAccent,
    required this.accentText,
    required this.success,
    required this.danger,
    required this.containerHigh,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.error,
    required this.onError,
    required this.errorContainer,
    required this.onErrorContainer,
    required this.onSuccess,
    required this.successContainer,
    required this.onSuccessContainer,
    required this.warning,
    required this.onWarning,
    required this.warningContainer,
    required this.onWarningContainer,
    required this.disabledFg,
    required this.disabledBg,
    required this.focus,
    required this.divider,
    required this.skeletonBase,
    required this.skeletonHighlight,
  });

  final Color bg;
  final Color surface;
  final Color container;
  final Color ink;
  final Color muted;
  final Color line;
  final Color outline;
  final Color primary;
  final Color onPrimary;
  final Color primaryContainer;
  final Color onPrimaryContainer;
  final Color accent;
  final Color onAccent;
  final Color accentText;
  final Color success;
  final Color danger;
  final Color containerHigh;
  final Color secondary;
  final Color onSecondary;
  final Color secondaryContainer;
  final Color onSecondaryContainer;
  final Color error;
  final Color onError;
  final Color errorContainer;
  final Color onErrorContainer;
  final Color onSuccess;
  final Color successContainer;
  final Color onSuccessContainer;
  final Color warning;
  final Color onWarning;
  final Color warningContainer;
  final Color onWarningContainer;
  final Color disabledFg;
  final Color disabledBg;
  final Color focus;
  final Color divider;
  final Color skeletonBase;
  final Color skeletonHighlight;

  static const AppColors light = AppColors(
    bg: Color(0xFFFFFFFF),
    surface: Color(0xFFFFFFFF),
    container: Color(0xFFF4F4F7),
    ink: Color(0xFF111113),
    muted: Color(0xFF55555F),
    line: Color(0xFFE4E4EA),
    outline: Color(0xFF8A8A96),
    primary: Color(0xFF5B3DF5),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFECE8FF),
    onPrimaryContainer: Color(0xFF2A1A8A),
    accent: Color(0xFF111113),
    onAccent: Color(0xFFFFFFFF),
    accentText: Color(0xFF111113),
    success: Color(0xFF1B7A43),
    danger: Color(0xFFB3261E),
    containerHigh: Color(0xFFEAEAF0),
    secondary: Color(0xFF111113),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE9E9EE),
    onSecondaryContainer: Color(0xFF111113),
    error: Color(0xFFB3261E),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFDECEA),
    onErrorContainer: Color(0xFF5F1410),
    onSuccess: Color(0xFFFFFFFF),
    successContainer: Color(0xFFE3F4EA),
    onSuccessContainer: Color(0xFF0B3D20),
    warning: Color(0xFF8A5A00),
    onWarning: Color(0xFFFFFFFF),
    warningContainer: Color(0xFFFFF1D6),
    onWarningContainer: Color(0xFF4A2F00),
    disabledFg: Color(0xFF8A8A96),
    disabledBg: Color(0xFFEDEDF1),
    focus: Color(0xFF5B3DF5),
    divider: Color(0xFFE4E4EA),
    skeletonBase: Color(0xFFF4F4F7),
    skeletonHighlight: Color(0xFFEAEAF0),
  );

  static const AppColors dark = AppColors(
    bg: Color(0xFF0C0C0E),
    surface: Color(0xFF131316),
    container: Color(0xFF1C1C21),
    ink: Color(0xFFF4F4F6),
    muted: Color(0xFFA6A6B3),
    line: Color(0xFF2A2A31),
    outline: Color(0xFF7A7A88),
    primary: Color(0xFFA593FF),
    onPrimary: Color(0xFF1A0F57),
    primaryContainer: Color(0xFF3A2C99),
    onPrimaryContainer: Color(0xFFE6E0FF),
    accent: Color(0xFFF4F4F6),
    onAccent: Color(0xFF111113),
    accentText: Color(0xFFF4F4F6),
    success: Color(0xFF6BD79B),
    danger: Color(0xFFFFB4AB),
    containerHigh: Color(0xFF26262C),
    secondary: Color(0xFFF4F4F6),
    onSecondary: Color(0xFF111113),
    secondaryContainer: Color(0xFF26262C),
    onSecondaryContainer: Color(0xFFF4F4F6),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    onSuccess: Color(0xFF00391C),
    successContainer: Color(0xFF12432A),
    onSuccessContainer: Color(0xFFC6F0D6),
    warning: Color(0xFFFFC857),
    onWarning: Color(0xFF2B1A00),
    warningContainer: Color(0xFF4A3300),
    onWarningContainer: Color(0xFFFFE2A8),
    disabledFg: Color(0xFF6E6E7A),
    disabledBg: Color(0xFF1E1E23),
    focus: Color(0xFFA593FF),
    divider: Color(0xFF2A2A31),
    skeletonBase: Color(0xFF1C1C21),
    skeletonHighlight: Color(0xFF26262C),
  );

  @override
  AppColors copyWith({
    Color? bg,
    Color? surface,
    Color? container,
    Color? ink,
    Color? muted,
    Color? line,
    Color? outline,
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? onPrimaryContainer,
    Color? accent,
    Color? onAccent,
    Color? accentText,
    Color? success,
    Color? danger,
    Color? containerHigh,
    Color? secondary,
    Color? onSecondary,
    Color? secondaryContainer,
    Color? onSecondaryContainer,
    Color? error,
    Color? onError,
    Color? errorContainer,
    Color? onErrorContainer,
    Color? onSuccess,
    Color? successContainer,
    Color? onSuccessContainer,
    Color? warning,
    Color? onWarning,
    Color? warningContainer,
    Color? onWarningContainer,
    Color? disabledFg,
    Color? disabledBg,
    Color? focus,
    Color? divider,
    Color? skeletonBase,
    Color? skeletonHighlight,
  }) {
    return AppColors(
      bg: bg ?? this.bg,
      surface: surface ?? this.surface,
      container: container ?? this.container,
      ink: ink ?? this.ink,
      muted: muted ?? this.muted,
      line: line ?? this.line,
      outline: outline ?? this.outline,
      primary: primary ?? this.primary,
      onPrimary: onPrimary ?? this.onPrimary,
      primaryContainer: primaryContainer ?? this.primaryContainer,
      onPrimaryContainer: onPrimaryContainer ?? this.onPrimaryContainer,
      accent: accent ?? this.accent,
      onAccent: onAccent ?? this.onAccent,
      accentText: accentText ?? this.accentText,
      success: success ?? this.success,
      danger: danger ?? this.danger,
      containerHigh: containerHigh ?? this.containerHigh,
      secondary: secondary ?? this.secondary,
      onSecondary: onSecondary ?? this.onSecondary,
      secondaryContainer: secondaryContainer ?? this.secondaryContainer,
      onSecondaryContainer: onSecondaryContainer ?? this.onSecondaryContainer,
      error: error ?? this.error,
      onError: onError ?? this.onError,
      errorContainer: errorContainer ?? this.errorContainer,
      onErrorContainer: onErrorContainer ?? this.onErrorContainer,
      onSuccess: onSuccess ?? this.onSuccess,
      successContainer: successContainer ?? this.successContainer,
      onSuccessContainer: onSuccessContainer ?? this.onSuccessContainer,
      warning: warning ?? this.warning,
      onWarning: onWarning ?? this.onWarning,
      warningContainer: warningContainer ?? this.warningContainer,
      onWarningContainer: onWarningContainer ?? this.onWarningContainer,
      disabledFg: disabledFg ?? this.disabledFg,
      disabledBg: disabledBg ?? this.disabledBg,
      focus: focus ?? this.focus,
      divider: divider ?? this.divider,
      skeletonBase: skeletonBase ?? this.skeletonBase,
      skeletonHighlight: skeletonHighlight ?? this.skeletonHighlight,
    );
  }

  @override
  AppColors lerp(ThemeExtension<AppColors>? other, double t) {
    if (other is! AppColors) return this;
    return AppColors(
      bg: Color.lerp(bg, other.bg, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      container: Color.lerp(container, other.container, t)!,
      ink: Color.lerp(ink, other.ink, t)!,
      muted: Color.lerp(muted, other.muted, t)!,
      line: Color.lerp(line, other.line, t)!,
      outline: Color.lerp(outline, other.outline, t)!,
      primary: Color.lerp(primary, other.primary, t)!,
      onPrimary: Color.lerp(onPrimary, other.onPrimary, t)!,
      primaryContainer: Color.lerp(
        primaryContainer,
        other.primaryContainer,
        t,
      )!,
      onPrimaryContainer: Color.lerp(
        onPrimaryContainer,
        other.onPrimaryContainer,
        t,
      )!,
      accent: Color.lerp(accent, other.accent, t)!,
      onAccent: Color.lerp(onAccent, other.onAccent, t)!,
      accentText: Color.lerp(accentText, other.accentText, t)!,
      success: Color.lerp(success, other.success, t)!,
      danger: Color.lerp(danger, other.danger, t)!,
      containerHigh: Color.lerp(containerHigh, other.containerHigh, t)!,
      secondary: Color.lerp(secondary, other.secondary, t)!,
      onSecondary: Color.lerp(onSecondary, other.onSecondary, t)!,
      secondaryContainer: Color.lerp(
        secondaryContainer,
        other.secondaryContainer,
        t,
      )!,
      onSecondaryContainer: Color.lerp(
        onSecondaryContainer,
        other.onSecondaryContainer,
        t,
      )!,
      error: Color.lerp(error, other.error, t)!,
      onError: Color.lerp(onError, other.onError, t)!,
      errorContainer: Color.lerp(errorContainer, other.errorContainer, t)!,
      onErrorContainer: Color.lerp(
        onErrorContainer,
        other.onErrorContainer,
        t,
      )!,
      onSuccess: Color.lerp(onSuccess, other.onSuccess, t)!,
      successContainer: Color.lerp(
        successContainer,
        other.successContainer,
        t,
      )!,
      onSuccessContainer: Color.lerp(
        onSuccessContainer,
        other.onSuccessContainer,
        t,
      )!,
      warning: Color.lerp(warning, other.warning, t)!,
      onWarning: Color.lerp(onWarning, other.onWarning, t)!,
      warningContainer: Color.lerp(
        warningContainer,
        other.warningContainer,
        t,
      )!,
      onWarningContainer: Color.lerp(
        onWarningContainer,
        other.onWarningContainer,
        t,
      )!,
      disabledFg: Color.lerp(disabledFg, other.disabledFg, t)!,
      disabledBg: Color.lerp(disabledBg, other.disabledBg, t)!,
      focus: Color.lerp(focus, other.focus, t)!,
      divider: Color.lerp(divider, other.divider, t)!,
      skeletonBase: Color.lerp(skeletonBase, other.skeletonBase, t)!,
      skeletonHighlight: Color.lerp(
        skeletonHighlight,
        other.skeletonHighlight,
        t,
      )!,
    );
  }

  /// Every role name, in declaration order (used by token tests).
  static const List<String> roles = <String>[
    'bg',
    'surface',
    'container',
    'ink',
    'muted',
    'line',
    'outline',
    'primary',
    'onPrimary',
    'primaryContainer',
    'onPrimaryContainer',
    'accent',
    'onAccent',
    'accentText',
    'success',
    'danger',
    'containerHigh',
    'secondary',
    'onSecondary',
    'secondaryContainer',
    'onSecondaryContainer',
    'error',
    'onError',
    'errorContainer',
    'onErrorContainer',
    'onSuccess',
    'successContainer',
    'onSuccessContainer',
    'warning',
    'onWarning',
    'warningContainer',
    'onWarningContainer',
    'disabledFg',
    'disabledBg',
    'focus',
    'divider',
    'skeletonBase',
    'skeletonHighlight',
  ];

  Color byName(String role) => switch (role) {
    'bg' => bg,
    'surface' => surface,
    'container' => container,
    'ink' => ink,
    'muted' => muted,
    'line' => line,
    'outline' => outline,
    'primary' => primary,
    'onPrimary' => onPrimary,
    'primaryContainer' => primaryContainer,
    'onPrimaryContainer' => onPrimaryContainer,
    'accent' => accent,
    'onAccent' => onAccent,
    'accentText' => accentText,
    'success' => success,
    'danger' => danger,
    'containerHigh' => containerHigh,
    'secondary' => secondary,
    'onSecondary' => onSecondary,
    'secondaryContainer' => secondaryContainer,
    'onSecondaryContainer' => onSecondaryContainer,
    'error' => error,
    'onError' => onError,
    'errorContainer' => errorContainer,
    'onErrorContainer' => onErrorContainer,
    'onSuccess' => onSuccess,
    'successContainer' => successContainer,
    'onSuccessContainer' => onSuccessContainer,
    'warning' => warning,
    'onWarning' => onWarning,
    'warningContainer' => warningContainer,
    'onWarningContainer' => onWarningContainer,
    'disabledFg' => disabledFg,
    'disabledBg' => disabledBg,
    'focus' => focus,
    'divider' => divider,
    'skeletonBase' => skeletonBase,
    'skeletonHighlight' => skeletonHighlight,
    _ => throw ArgumentError.value(role, 'role'),
  };
}
